// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {client} from '../models';

export function Download(arg1:string):Promise<void>;

export function Fetch(arg1:client.Request):Promise<client.Download>;
